# ───────────────────────────────────────────────────────────────
# render.yaml — ShopVerse Infrastructure as Code
# ───────────────────────────────────────────────────────────────
services:

  # ── Backend API (Server) ─────────────────────────────────────
  - type: web
    name: shopverse-server
    runtime: docker
    dockerfilePath: ./server/Dockerfile
    dockerContext: ./server
    plan: free
    region: singapore
    branch: main
    autoDeploy: true
    envVars:
      - key: PORT
        value: 8080
      - key: CLIENT_URL
        value: https://shopverse-client.onrender.com
      - key: ADMIN_URL
        value: https://shopverse-admin-9t5r.onrender.com
      - key: MONGO_URI
        value: mongodb+srv://rizsameer001_db_user:apyzUNvvS0p0318K@cluster0.xbnnnsq.mongodb.net/shopverse?appName=Cluster0
      - key: JWT_SECRET
        value: "your-very-secret-key-here"
      - key: JWT_EXPIRATION
        value: 86400000

  # ── Admin Dashboard ──────────────────────────────────────────
  - type: web
    name: shopverse-admin
    runtime: docker
    dockerfilePath: ./admin/Dockerfile
    dockerContext: ./admin
    plan: free
    region: singapore
    branch: main
    autoDeploy: true
    envVars:
      - key: VITE_API_URL
        value: https://shopverse-server-sfvj.onrender.com

  # ── Client Store Frontend ────────────────────────────────────
  - type: web
    name: shopverse-client
    runtime: docker
    dockerfilePath: ./client/Dockerfile
    dockerContext: ./client
    plan: free
    region: singapore
    branch: main
    autoDeploy: true
    envVars:
      - key: VITE_API_URL
        value: https://shopverse-server-sfvj.onrender.com