services:
  - type: web
    name: shopverse-api
    env: node
    plan: free
    region: singapore
    branch: main
    autoDeploy: true
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: JWT_EXPIRE
        value: 30d
      - key: JWT_COOKIE_EXPIRE
        value: 30
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: SMTP_HOST
        sync: false
      - key: SMTP_PORT
        value: 587
      - key: SMTP_EMAIL
        sync: false
      - key: SMTP_PASSWORD
        sync: false
      - key: FROM_EMAIL
        sync: false
      - key: FROM_NAME
        value: ShopVerse
      - key: CLIENT_URL
        sync: false
      - key: ADMIN_URL
        sync: false
